src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 */
class Booking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $status;

    /**
     * @ORM\ManyToOne(targetEntity=Box::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    public ?Box $box;

    /**
     * @ORM\OneToOne(targetEntity=Order::class, mappedBy="booking", cascade={"persist", "remove"})
     */
    public ?Order $linkedOrder;

    /**
     * @ORM\Column(type="integer")
     */
    public ?int $box_quantity;

    /**
     * @ORM\Column(type="date")
     */
    public ?DateTimeInterface $date;

    /**
     * @ORM\Column(type="time")
     */
    public ?DateTimeInterface $time;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public ?string $delivery_address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public ?string $appointment_address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public ?string $customerId;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public ?string $chiefId;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getBox(): ?Box
    {
        return $this->box;
    }

    public function setBox(?Box $box): self
    {
        $this->box = $box;

        return $this;
    }

    public function getLinkedOrder(): ?Order
    {
        return $this->linkedOrder;
    }

    public function setLinkedOrder(Order $linkedOrder): self
    {
        // set the owning side of the relation if necessary
        if ($linkedOrder->getBooking() !== $this) {
            $linkedOrder->setBooking($this);
        }

        $this->linkedOrder = $linkedOrder;

        return $this;
    }

    public function getBoxQuantity(): ?int
    {
        return $this->box_quantity;
    }

    public function setBoxQuantity(int $box_quantity): self
    {
        $this->box_quantity = $box_quantity;

        return $this;
    }

    public function getDate(): ?DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getTime(): ?DateTimeInterface
    {
        return $this->time;
    }

    public function setTime(DateTimeInterface $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getDeliveryAddress(): ?string
    {
        return $this->delivery_address;
    }

    public function setDeliveryAddress(string $delivery_address): self
    {
        $this->delivery_address = $delivery_address;

        return $this;
    }

    public function getAppointmentAddress(): ?string
    {
        return $this->appointment_address;
    }

    public function setAppointmentAddress(string $appointment_address): self
    {
        $this->appointment_address = $appointment_address;

        return $this;
    }

    public function getCustomerId(): ?string
    {
        return $this->customerId;
    }

    public function setCustomerId(string $customerId): self
    {
        $this->customerId = $customerId;

        return $this;
    }

    public function getChiefId(): ?string
    {
        return $this->chiefId;
    }

    public function setChiefId(string $chiefId): self
    {
        $this->chiefId = $chiefId;

        return $this;
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\UserCustomer;
use App\Repository\BookingRepository;
use App\Repository\BoxRepository;
use App\Repository\MealRepository;
use App\Repository\UserChiefRepository;
use Psr\Container\ContainerExceptionInterface;
use Psr\Container\NotFoundExceptionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

class BookingController extends AbstractController
{
    /**
     * @throws ContainerExceptionInterface
     * @throws NotFoundExceptionInterface
     */
    #[Route('/reservations', name: 'orders')]
    public function index(BookingRepository $bookingRepository, UserChiefRepository $userChiefRepository, BoxRepository $boxRepository, MealRepository $mealRepository): Response
    {
        if( $this->container->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            $user = $this->get('security.token_storage')->getToken()->getUser();
            $orders = $bookingRepository->findAllUserOrders($user->id);
            foreach ($orders as $order) {
                $chief = $userChiefRepository->find($order->chiefId);
                $box = $boxRepository->find($order->box);
                $meal = $mealRepository->find($box->getMeal());
                $order->chiefId = $chief->getFirstName() . " " . $chief->getLastName();
                $order->meal = $meal->getName();
            }

            return $this->render('booking/index.html.twig', [
                'orders' => $orders,
            ]);
        } else {
            return $this->redirectToRoute('app_customer_login');
        }
    }
}

templates/booking/index.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('home') }}
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block title %}Liste des commandes{% endblock %}
{% block body %}
    <style>
        .ordersTitle {
            font-family: Sofia Pro, serif;
            font-style: normal;
            font-size: 31px;
            line-height: 113.7%;
            color: #EFAF00;
        }

        .ordersTable::-webkit-scrollbar {
            width: 8px !important;
            background-color: #fff !important;
        }

        .ordersTable::-webkit-scrollbar-thumb {
            background: #EFAF00 !important;
            border-radius: 10px !important;
        }

        .ordersTable .table tbody tr:hover {
            cursor: pointer;
        }

        .ordersTable tbody td, .ordersTable tbody th {
            color: #707070;
        }
    </style>
    <div class="app">
        {{ include('layout/navbar/index.html.twig') }}
        <div class="vh-100">
            <div class="swpSlideContainer ordersTable overflow-auto ml-0 w-100 position-absolute formContainer">
                <div class="ordersTitle mx-auto text-center font-weight-bold mb-3 mt-4">Liste des commandes passées</div>
                <table class="table table-striped px-5 mt-5 table-sm table-hover mb-0 text-center" style="border-collapse: separate; border-spacing: 0">
                    <thead class="bg-white position-sticky top-0 border-bottom border-dark" style="z-index: 1">
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Heure</th>
                        <th scope="col">Plat</th>
                        <th scope="col">Box</th>
                        <th scope="col">Quantité</th>
                        <th scope="col">Prix</th>
                        <th scope="col">Chef</th>
                        <th scope="col">Adresse de livraison</th>
                        <th scope="col">Adresse de rdv</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}
                        <tr class="position-relative">
                            <th scope="row">{{ order.date|date("d/m/Y") }}</th>
                            <td>{{ order.time|date("H:i") }}</td>
                            <td>{{ order.meal }}</td>
                            <td>{{ order.box.name }}</td>
                            <td>{{ order.box_quantity }}x</td>
                            <td>{{ order.linkedOrder.price }}€</td>
                            <td>{{ order.chiefId }}</td>
                            <td>{{ order.deliveryAddress }}</td>
                            <td>{{ order.appointmentAddress }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            </div>
        </div>
        <div class="position-absolute pb-1 w-100" id="socialIcons" style="z-index: 1">
            <a href="https://facebook.com" class="mx-2" title="Page Facebook"><i class="fa-brands fa-facebook"></i></a>
            <a href="https://instagram.com" class="mx-2" title="Page Instagram"><i class="fa-brands fa-instagram"></i></a>
            <a href="https://linkedin.com" class="mx-2" title="Page Linkedin"><i class="fa-brands fa-linkedin-in"></i></a>
            <a href="https://youtube.com" class="mx-2" title="Chaine Youtube"><i class="fa-brands fa-youtube"></i></a>
        </div>
    </div>

{% endblock %}