src/Entity/Meal.php
<?php

namespace App\Entity;

use App\Repository\MealRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MealRepository::class)
 */
class Meal
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    public $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public ?string $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    public ?string $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public ?string $picture;

    /**
     * @ORM\OneToMany(targetEntity=Box::class, mappedBy="meal", orphanRemoval=true)
     */
    public Collection $boxes;

    /**
     * @ORM\ManyToOne(targetEntity=FoodCategory::class, inversedBy="meals")
     * @ORM\JoinColumn(nullable=false)
     */
    public ?FoodCategory $food_category;

    public function __construct()
    {
        $this->boxes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * @return Collection|Box[]
     */
    public function getBoxes(): Collection
    {
        return $this->boxes;
    }

    public function addBox(Box $box): self
    {
        if (!$this->boxes->contains($box)) {
            $this->boxes[] = $box;
            $box->setMeal($this);
        }

        return $this;
    }

    public function removeBox(Box $box): self
    {
        if ($this->boxes->removeElement($box)) {
            // set the owning side to null (unless already changed)
            if ($box->getMeal() === $this) {
                $box->setMeal(null);
            }
        }

        return $this;
    }

    public function getFoodCategory(): ?FoodCategory
    {
        return $this->food_category;
    }

    public function setFoodCategory(?FoodCategory $food_category): self
    {
        $this->food_category = $food_category;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\BoxRepository;
use App\Repository\UserChiefRepository;
use App\Repository\MealRepository;
use App\Repository\FoodCategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(MealRepository $mealRepository, FoodCategoryRepository $foodCategoryRepository, BoxRepository $boxRepository, UserChiefRepository $chiefRepository): Response
    {
        $food_categories = $foodCategoryRepository->findAllOrderedBy("id");
        $chiefs = $chiefRepository->findAllOrderedBy("id");
        $meals = $mealRepository->findAllOrderedBy("id");
        $boxes = $boxRepository->findAllOrderedBy("id");


        foreach ($meals as $meal) {
            $mealBoxes = array_filter($boxes, function ($var) use ($meal) {
                return ($var->meal->id == $meal->id);
            });
            $meal->meal_boxes = $mealBoxes;
        }

        return $this->render('home/index.html.twig', [
            'food_categories' => $food_categories,
            'meals' => $meals,
            'chiefs' => $chiefs,
        ]);
    }
}

templates/home/slides/calendar.html.twig
<div class="swiper-slide d-flex flex-row align-items-end">
    <div class="swpSlideContainer w-100" id="swpCalendarContainer">
        <div class="row h-100 mx-0">
            <div class="col-6 px-0 d-flex justify-content-end">
                <div class="formBlock col-7 mr-5 mb-2 py-2 px-5 bg-white text-center d-flex flex-column justify-content-between">
                    <div class="mb-3">
                        <div class="formTitle mt-1 text-left">Heure et date</div>
                        <div class="formSubTitle mt-1 text-left">Renseignez vos informations de livraison</div>
                    </div>
                    <div class="form-group">
                        <label class="w-100 text-left mb-1 small" for="deliveryAddress">Adresse de livraison box</label>
                        <input type="text" maxlength="255" id="deliveryAddress" name="deliveryAddress" placeholder="4 rue d’adresse de livraison" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label class="w-100 text-left mb-1 small" for="appointmentAddress">Adresse du rendez-vous</label>
                        <input type="text" maxlength="255" id="appointmentAddress" name="appointmentAddress" placeholder="4 rue d’adresse de rdv" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label class="w-100 text-left mb-1 small" for="orderDate">Quelle est la date ?</label>
                        <input type="date" id="orderDate" name="orderDate" class="form-control" min="{{ "now"|date("Y-m-d") }}" required>
                    </div>
                    <div class="form-group">
                        <label class="w-100 text-left mb-1 small" for="orderTime">Quelle est l’heure ?</label>
                        <input type="time" id="orderTime" name="orderTime" class="form-control" required>
                    </div>
                    <div class="mainBtn validateBtn btn mx-auto mb-2" style="width: fit-content" data-slide-to="6">Validation des informations</div>
                    <div class="formText text-justify mb-1" style="font-size: 70%">
                        <i class="fa-solid fa-circle-info fa-lg"></i> Votre box arrive à la même date que votre
                        rendez-vous, afin d’avoir des produits frais à utiliser dans la journée même.
                    </div>
                </div>
            </div>
            <div class="col-6 px-0 d-flex justify-content-center">
                <img class="w-75" src="{{ asset('build/images/slides/woman-calendar.svg') }}" alt="Calendar" title="Calendar"/>
            </div>
        </div>
    </div>
</div>

templates/home/slides/chiefs.html.twig
<style>
    .chiefSlogan {
        font-family: 'ABeeZee', serif;
        font-style: italic;
        font-size: 23px;
        color: #EFAF00;
    }

    .chiefDescription {
        font-family: 'Roboto', serif;
        color: #BDB4A7;
        font-weight: 300;
        line-height: 26px;
    }

    .chiefLore {
        border-radius: 4px;
        height: 254px;
    }

    .chiefEquipments {
        background: rgba(239, 175, 0, 0.1);
        border-radius: 4px;
    }

    .chiefEquipments img {
        width: 40px;
        height: 40px;
    }

    .chiefEquipmentsLabel {
        color: #BDB4A7;
        font-family: 'Roboto', serif;
    }
    
    .chiefEquipmentName {
        font-family: 'Roboto', serif;
        font-size: 13px;
        color: #BDB4A7;
    }
</style>
<div class="swiper-slide d-flex flex-row align-items-end">
    <div class="swpSlideContainer" id="swpChiefsContainer">
        <div class="pageTitle w-75 mt-4 mb-3 px-3">
            <h2>Choisissez votre chef</h2>
        </div>
        <div id="chiefsCarousel" class="carousel slide" data-interval="false" data-ride="carousel">
            <div class="carousel-inner">
                {% for chief in chiefs %}
                    <div class="carousel-item {{ loop.first ? 'active' }}" data-chief="{{ chief.firstName ~ chief.lastName }}" data-chief-id="{{ chief.id }}">
                        <div class="d-flex mt-2">
                            <div class="col-7 ml-5">
                                <div class="chiefLore bg-white px-5 py-4 text-center">
                                    <div class="chiefSlogan">"{{ chief.slogan }}"</div>
                                    <hr class="w-100">
                                    <div class="chiefDescription">{{ chief.description }}</div>
                                </div>
                                <div class="chiefEquipments p-4 mt-3">
                                    <div class="chiefEquipmentsLabel text-center">Je possèdes comme matériel à emporter</div>
                                    <div class="d-flex mt-4 justify-content-around">
                                        {% for equipment in chief.equipments %}
                                            <div class="d-flex flex-column mt-2">
                                                <img class="mx-auto" src="{{ asset('build/images/equipments/' ~ equipment|slug ~ '.svg' ) }}" alt="{{ equipment|slug }}">
                                                <div class="chiefEquipmentName mt-2"> {{ equipment }}</div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <div class="col-5">
                                <img class="h-100" src="{{ asset('build/images/chiefs/' ~ chief.picture ) }}" alt="{{ chief.firstName ~ chief.lastName }}">
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="d-flex justify-content-end align-items-center mr-5 mt-3" id="chiefCarouselIndicators">
            <a class="mr-2" href="#chiefsCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon rounded-circle p-3" aria-hidden="true"></span>
                <span class="sr-only">Précédent</span>
            </a>
            <a class="ml-2" href="#chiefsCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon rounded-circle p-3" aria-hidden="true"></span>
                <span class="sr-only">Suivant</span>
            </a>
            <div class="mainBtn validateBtn btn px-5 ml-4 mr-5" data-slide-to="5">Choisir ce chef</div>
        </div>
    </div>
</div>

templates/home/slides/confirm.html.twig
<style>
    .confirmThxText {
        background: rgba(239, 175, 0, 0.2);
        border-radius: 4px;
        font-family: 'Roboto', serif;
        color: #4E4E4E;
    }
</style>
<div class="swiper-slide d-flex flex-row align-items-end">
    <div class="swpSlideContainer" id="swpConfirmContainer">
        <div class="pageTitle confirmWaiting h-100 d-flex justify-content-center align-items-center">
            <h2>En attente d'informations pour valider la commande</h2>
        </div>
        <div class="confirmCompleted d-none flex-column">
            <div class="pageTitle w-75 mt-4 mb-5 px-3">
                <h2>Bravo ! Confirmation de votre réservation !</h2>
            </div>
            <div class="d-flex">
                <div class="col-7">
                    <div class="p-4 confirmThxText">Merci pour votre réservation ! <br>Toutes les informations vous sont envoyées sur votre adresse mail.</div>
                </div>
                <div class="col-5">
                    <img src="{{ asset('build/images/slides/woman-order.svg') }}" alt="woman-order">
                </div>
            </div>
        </div>
    </div>
</div>

templates/home/slides/cookingtypes.html.twig
<style>
    .pageTitle {color: #4E4E4E}

    .cardTitle {
        font-family: Sofia Pro, serif;
        font-style: normal;
        font-weight: bold;
        font-size: 18px;
        line-height: 113.7%;
    }

    .choiceCard {
        background: rgba(239, 175, 0, 0.1);
        border-radius: 4px;
    }

    .choiceCard:hover {
        cursor: pointer;
        background: rgba(239, 175, 0, 0.2);
    }

    .choiceCard.active {background: rgb(239 175 0 / 25%)}

    .choiceRadio {color: white}

    .choiceCard.active .choiceRadio {color: #E7871E}

    .choiceCard.active .cardText {opacity: 1}

    .text2 {color: #727272}

    .cardText {
        font-family: Roboto, serif;
        line-height: 19px;
        color: #A39B9B;
        opacity: 0.5;
    }

    .cakeFountain {
        width: 10rem;
        right: 0;
        bottom: 0;
    }

    .cookingTypeName {
        font-family: 'Roboto', serif;
        line-height: 19px;
        color: #BDB4A7;
    }

</style>
<div class="swiper-slide d-flex flex-row align-items-end">
    <div class="swpSlideContainer" id="swpCookingTypesContainer">
        <div class="firstStep">
            <div class="pageTitle w-75 mt-4 mb-5 px-3">
                <h2>Souhaitez-vous réserver pour un évènement ou un apprentissage ?</h2>
            </div>
            <div class="choiceCardsList mx-auto w-75 d-flex">
                <div class="choiceCard active ml-5 mt-3 px-4 pb-4 pt-3">
                    <div class="text-center">
                        <i class="fa-regular fa-circle-dot fa-lg choiceRadio active"></i>
                    </div>
                    <div class="text2 text-center">
                        <div class="cardTitle pt-1 pb-3">Pour un évènement</div>
                    </div>
                    <div class="text3">
                        <p class="cardText active">Pour un mariage, un anniversaire, une soirée d’entreprise... <br> CheFinder vous propose ses services de cuisine à domicile et s’occupe de tout</p>
                    </div>
                </div>
                <div class="choiceCard ml-5 mt-3 px-4 pb-4 pt-3">
                    <div class="text-center">
                        <i class="fa-regular fa-circle-dot fa-lg choiceRadio"></i>
                    </div>
                    <div class="text2 text-center">
                        <div class="cardTitle pt-1 pb-3">Pour un apprentissage</div>
                    </div>
                    <div class="text3">
                        <p class="cardText">Tu souhaites apprendre à cuisiner ? <br> CheFinder t’offre l’opportunité de suivre un apprentissage en cuisine avec un de nos chefs cuisiniers.</p>
                    </div>
                </div>
            </div>
            <div class="mx-auto w-75 d-flex justify-content-end mt-4">
                <div class="mainBtn validateBtn switchStep btn">Etape suivante</div>
            </div>
            <img src="{{ asset('build/images/slides/cake-fountain.png') }}" class="cakeFountain position-absolute" alt="cake-fountain">
        </div>
        <div class="secondStep d-none">
            <div class="pageTitle w-75 mt-3 px-3">
                <h2>Choisissez le type de cuisine</h2>
            </div>
            <div class="d-flex mt-5">
                <div class="col-4">
                    <div class="overflowedList mealTypeList h-50 pb-4 d-flex flex-column overflow-auto">
                        {% for food_category in food_categories %}
                            <div class="listItem d-flex align-items-center p-2 mb-2 mr-2 {{ loop.first ? 'active' }}" data-meal-type="{{ food_category.id }}">
                                <img src="{{ asset('build/images/cooking-types/' ~ food_category.picture ) }}" alt="{{ food_category.name }}">
                                <div class="cookingTypeName ml-3">{{ food_category.name }}{% if food_category.description %}<br>{{ food_category.description }}{% endif %}</div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="d-flex mt-2">
                        <div class="w-25 mr-2 mainBtn returnBtn switchStep btn">Retour</div>
                        <div class="w-75 ml-2 mainBtn validateBtn btn" data-slide-to="3">Valider son type de cuisine</div>
                    </div>
                </div>
                <div class="col-8 pr-0 d-flex justify-content-center">
                    <img src="{{ asset('build/images/slides/chief-woman-working.svg') }}" class="position-absolute" alt="chief-woman-working">
                </div>
            </div>
        </div>
    </div>
</div>

templates/home/slides/hello.html.twig
<style>
    .greetingsTitle {
        font-family: Sofia Pro, serif;
        font-style: normal;
        font-size: 31px;
        line-height: 113.7%;
        color: #4E4E4E;
    }

    .greetingsText {
        font-family: Roboto, serif;
        font-style: normal;
        font-size: 16px;
        line-height: 19px;
        color: #A39B9B;
    }
</style>
<div class="swiper-slide d-flex flex-row align-items-end">
    <div class="swpSlideContainer w-100">
        <div class="row h-100">
            <div class="col-4 h-100 d-flex flex-column justify-content-start mt-5">
                <h1 class="greetingsTitle font-weight-bold mb-3 mt-5">Bienvenue chez CheFinder, réserver en ligne votre chef cuisinier</h1>
                <h2 class="greetingsText font-weight-normal text-justify">
                    Tu aimerais qu’un chef cuisinier vienne te cuisiner de bons repas à domicile ?
                    Tu aimerais apprendre de nouvelles recettes ? Ne bouge pas ! Tu es sur le bon site.
                </h2>
                {% if app.user %}
                    <div class="mainBtn validateBtn btn mb-2 mt-5" data-slide-to="1">Réserver un chef</div>
                {% else %}
                    <div class="mainBtn validateBtn btn mb-2 mt-5" data-toggle="modal" data-target="#loginWarningModal">Réserver un chef</div>
                {% endif %}
            </div>
            <div class="col-8 h-100">
                <img class="vh-100" src="{{ asset('build/images/slides/Cuisto.png') }}" alt="Chef">
            </div>
        </div>
    </div>
</div>

templates/home/slides/payment.html.twig
<style>
    .paymentModel {
        border: 3px solid #E1D8CD;
        border-radius: 7px;
        height: fit-content;
    }

    .paymentModel img {
        width: 40px;
        height: 40px;
    }

    .paymentModel:hover {
        background: #f5f5f5 !important;
        cursor: pointer;
    }

    .paymentModel.active {
        border: 3px solid #EFAF00;
    }

    .paymentForm {
        background: rgba(239, 175, 0, 0.2);
        border-radius: 4px;
    }

    .paymentForm label {
        font-family: 'Sofia Pro', serif;
        font-weight: 500;
        font-size: 13px;
    }

    .paymentForm input {
        border: none;
        border-radius: 8px;
    }

    .paymentForm input:focus {
        border: none;
        box-shadow: none;
    }

    .paymentBoxCard {
        background: rgb(239 175 0 / 25%);
        border-radius: 4px;
    }

    .paymentOrderTitle {
        font-family: 'Sofia Pro', serif;
        font-weight: 500;
        font-size: 21px;
        color: #4E4E4E;
    }
</style>
<div class="swiper-slide d-flex flex-row align-items-end">
    <div class="swpSlideContainer" id="swpPaymentContainer">
        <div class="pageTitle w-75 mt-4 mb-5 px-3">
            <h2>Sélectionner votre mode de paiement</h2>
        </div>
        <div class="d-flex align-items-center">
            <p class="text-muted mx-3 my-0" style="font-size: smaller">Choisir votre carte de paiement :</p>
            <div class="d-flex ml-3 align-items-center">
                <div class="paymentModel bg-white px-3 mx-2 active"><img src="{{ asset('build/images/slides/visa-logo.svg') }}" alt="Visa"></div>
                <div class="paymentModel bg-white px-3 mx-2"><img src="{{ asset('build/images/slides/mastercard-logo.svg') }}" alt="Mastercard"></div>
                <div class="paymentModel bg-white px-3 mx-2"><img src="{{ asset('build/images/slides/paypal-logo.svg') }}" alt="Paypal"></div>
                <div class="paymentModel bg-white px-3 mx-2"><img src="{{ asset('build/images/slides/applepay-logo.svg') }}" alt="Apple Pay"></div>
                <div class="paymentModel bg-white px-3 mx-2"><img src="{{ asset('build/images/slides/googlepay-logo.svg') }}" alt="Google Pay"></div>
            </div>
        </div>
        <div class="d-flex justify-content-around mt-5 mx-5">
            <div class="paymentForm col-7">
                <div class="d-flex py-4 flex-column justify-content-around">
                    <div class="d-flex mt-2 flex-column align-content-around">
                        <div class="d-flex my-2 py-1 justify-content-start align-items-center">
                            <label class="col-4 mb-0 px-0 text-center text-secondary" for="creditCardNumber" style="">Votre numéro de carte :</label>
                            <input class="form-control col-7 py-2" type="text" name="creditCardNumber"
                                   placeholder="0000 0000 0000 0000" size="18" id="inputCardNumber" minlength="19" maxlength="19">
                        </div>
                        <div class="d-flex my-2 py-1 justify-content-start align-items-center">
                            <label class="col-4 mb-0 px-0 text-center text-secondary" for="creditCardExpireDate" style="">Votre date d’expiration :</label>
                            <input class="col-2 text-center form-control py-2" type="text" name="creditCardExpireDate"
                                   placeholder="MM/YY" size="6" id="inputCardExpDate" minlength="5" maxlength="5">
                        </div>
                        <div class="d-flex my-2 py-1 justify-content-start align-items-center">
                            <label class="col-4 mb-0 px-0 text-center text-secondary" for="creditCardCCV" style="">Votre nombre CVV :</label>
                            <input class="col-2 text-center form-control py-2" type="password" id="inputCardCcv"
                                   name="creditCardCCV" placeholder="000" size="1" minlength="3" maxlength="3">
                        </div>
                    </div>
                    <div class="d-flex justify-content-end mt-4">
                        <div class="validateOrderBtn mainBtn validateBtn btn disabled" data-slide-to="8" data-deliv-address="empty" data-meet-address="empty"
                             data-order-date="empty" data-order-time="empty" data-card-number="empty" data-card-exp="empty"
                             data-card-cvv="empty">Validation de votre commande</div>
                    </div>
                </div>
            </div>
            <div class="paymentOrderRecap d-flex flex-column justify-content-between col-4 bg-white px-3 pb-3 pt-4 mr-5" style="border-radius: 4px">
                <div class="paymentOrderTitle">Récapitulatif de votre commande :</div>
                <div class="choiceCardsList mt-5">
                    <div class="boxOrderTitle boxName mb-1 text-left">Box Basic</div>
                    <div class="paymentBoxCard px-4 pb-4 pt-3 active">
                        <p class="recapBoxText boxDescription text-muted mx-3">La box est composée d’ingrédients frais et savoureux pour les petits budgets.</p>
                        <hr class="w-100">
                        <div class="boxOrderDetails">
                            <div class="d-flex justify-content-between">
                                <div>Récapitulatif :</div>
                                <div class="d-flex">
                                    <div class="ordRecapQuantity">1</div>&nbsp;x&nbsp;<div class="ordRecapPrice">15</div>€
                                </div>
                            </div>
                            <div class="d-flex justify-content-between mt-1">
                                <div><u>Total de la commande :</u></div>
                                <div class="d-flex">
                                    <div class="orderPriceTotal">15</div>€
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/home/slides/recipes.html.twig
<style>
    .boxDetailsName {
        font-family: 'Roboto', serif;
        line-height: 19px;
        color: #4E4E4E;
    }
    
    .boxDetailsImg {
        width: 79px;
        height: 79px;
        top: -4%;
        border-radius: 14px;
        background-color: #fff8ef;
    }
    
    .boxOrderDetails {
        font-family: 'Roboto', serif;
        font-size: 12px;
        color: #E7871E;
        text-underline-position: under;
    }

    .boxOrderTitle {
        font-weight: 700;
        font-size: 18px;
        line-height: 113.7%;
        text-align: center;
        color: #E7871E;
    }

    .choiceCard.active .orderIncrementBtn:hover {background: #ffae55 !important;}

    .choiceCard .orderPrices, .choiceCard .boxOrderDetails {opacity: 0.35}

    .choiceCard.active .orderPrices, .choiceCard.active .boxOrderDetails {opacity: 1}
</style>
<div class="swiper-slide d-flex flex-row align-items-end">
    <div class="swpSlideContainer w-100" id="swpRecipesContainer">
        <div class="pageTitle w-75 mt-4 mb-5 px-3">
            <h2>Choisissez votre recette & votre Box</h2>
        </div>
        <div class="d-flex mt-5">
            <div class="col-4">
                <div class="overflowedList boxList h-50 pb-4 d-flex flex-column overflow-auto">
                    {% for meal in meals %}
                        <div class="listItem align-items-center p-2 mb-2 mr-2 {{ meal.foodCategory.id == '1' ? 'd-flex' : 'd-none' }} {{ loop.first ? 'active' }}" data-meal-type="{{ meal.foodCategory.id }}" data-box="{{ meal.name }}">
                            <img src="{{ asset('build/images/meals/' ~ meal.picture ) }}" alt="{{ meal.name }}">
                            <div class="cookingTypeName ml-3">{{ meal.name }}</div>
                        </div>
                    {% endfor %}
                </div>
                <div class="mt-2 w-100 mainBtn returnBtn btn" data-slide-to="2">Retour au choix du type de recette</div>
            </div>
            <div class="col-8 pr-0 boxOrder">
                {% for meal in meals %}
                    <div class="boxOrderItem {% if not loop.first %}d-none{% endif %}" data-recette-order="{{ meal.name }}">
                        <div class="boxOrderDetailsContainer d-flex justify-content-between bg-white p-4 mb-3" style="border-radius: 4px">
                            <div class="d-flex align-items-center">
                                <div style="width: 79px">
                                    <img class="boxDetailsImg position-absolute" src="{{ asset('build/images/meals/' ~ meal.picture ) }}" alt="{{ meal.name }}">
                                </div>
                                <div class="boxDetailsName ml-3">{{ meal.name }}</div>
                            </div>
                            <i class="fa-solid fa-chevron-down mt-2" style="color: #EFAF00"></i>
                        </div>
                        <div class="boxOrderDetailsContainer bg-white px-4 py-3" style="border-radius: 4px">
                            {% for meal_box in meal.meal_boxes %}
                                {% if loop.first %}
                                    <div class="choiceCardsList d-flex">
                                {% endif %}
                                <div class="w-50 {{ loop.first ? 'mr-2' : 'ml-2' }}">
                                    <div class="boxOrderTitle mb-1" data-box-id="{{ meal_box.id }}">{{ meal_box.name }}</div>
                                    <div class="choiceCard px-4 pb-4 pt-3 {{ loop.first ? 'active' }}">
                                        <div class="text-center mb-2">
                                            <i class="fa-regular fa-circle-dot fa-lg choiceRadio"></i>
                                        </div>
                                        <p class="text-center cardText mx-3">{{ meal_box.description }}</p>
                                        <div class="boxOrderDetails text-center"><u>En savoir plus</u></div>
                                        <div class="mt-4 d-flex justify-content-center orderPrices">
                                            <div class="d-flex">
                                                <div class="orderIncrementBtn text-white p-2" data-incr-type="-" style="background: #E7871E">-</div>
                                                <div class="orderQuantity bg-white p-2" style="color: #E7871E">1</div>
                                                <div class="orderIncrementBtn text-white p-2" data-incr-type="+" style="background: #E7871E">+</div>
                                            </div>
                                            <div class="d-flex bg-white py-2 px-3 ml-2 font-weight-bold" style="color: #E7871E">
                                                <div class="orderPrice">{{ meal_box.price }}</div>€
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% if loop.last %}
                                    </div>
                                    <hr class="w-100">
                                    <div class="boxOrderDetails d-flex">
                                        <div class="w-50">
                                            <div class="d-flex justify-content-between">
                                                <div>Récapitulatif :</div>
                                                <div class="d-flex">
                                                    <div class="ordRecapQuantity">1</div>&nbsp;x&nbsp;<div class="ordRecapPrice">{{ meal.meal_boxes|first.price }}</div>€
                                                </div>
                                            </div>
                                            <div class="d-flex justify-content-between mt-1">
                                                <div><u>Total de la commande :</u></div>
                                                <div class="d-flex"><div class="orderPriceTotal">{{ meal.meal_boxes|first.price }}</div>€</div>
                                            </div>
                                        </div>
                                        <div class="w-50 d-flex justify-content-end">
                                            <div class="mainBtn validateBtn btn" data-slide-to="4">Voir les chefs</div>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>